const SideBarLinks = [
  {
    id: 0,
    name: "Dashboard",
    icon: "fa fa-th-large",
    to: "/user/dashboard",
    role: "ROLE_USER",
  },
  {
    id: 1,
    name: "Transactions History",
    icon: "fa fa-exchange",
    to: "/user/transactions",
    role: "ROLE_USER",
  },
  {
    id: 2,
    name: "New Transaction",
    icon: "fa fa-calendar-plus-o",
    to: "/user/newTransaction",
    role: "ROLE_USER",
  },
  {
    id: 11,
    name: "Saved Transactions",
    icon: "fa fa-bookmark-o",
    to: "/user/savedTransactions",
    role: "ROLE_USER",
  },
  {
    id: 12,
    name: "Statistics",
    icon: "fa fa-line-chart",
    to: "/user/statistics",
    role: "ROLE_USER",
  },
  {
    id: 13,
    name: "Settings",
    icon: "fa fa-cog",
    to: "/user/settings",
    role: "ROLE_USER",
  },
  {
    id: 4,
    name: "Transactions",
    icon: "fa fa-exchange",
    to: "/admin/transactions",
    role: "ROLE_ADMIN",
  },
  {
    id: 5,
    name: "Users",
    icon: "fa fa-user-circle-o",
    to: "/admin/users",
    role: "ROLE_ADMIN",
  },
  {
    id: 9,
    name: "Create User",
    icon: "fa fa-user-plus",
    to: "/admin/users/new",
    role: "ROLE_ADMIN",
  },
  {
    id: 6,
    name: "Categories",
    icon: "fa fa-th-large",
    to: "/admin/categories",
    role: "ROLE_ADMIN",
  },
  {
    id: 7,
    name: "New Category",
    icon: "fa fa-plus-square",
    to: "/admin/newCategory",
    role: "ROLE_ADMIN",
  },
  {
    id: 8,
    name: "Settings",
    icon: "fa fa-cog",
    to: "/admin/settings",
    role: "ROLE_ADMIN",
  },
  {
    id: 19,
    name: "Organizations",
    icon: "fa fa-building-o",
    to: "/superadmin/organizations",
    role: "ROLE_SUPER_ADMIN",
  },
  {
    id: 20,
    name: "Create Organization",
    icon: "fa fa-plus-square-o",
    to: "/superadmin/organizations/new",
    role: "ROLE_SUPER_ADMIN",
  },
  {
    id: 17,
    name: "Manage Admins",
    icon: "fa fa-users",
    to: "/superadmin/admins",
    role: "ROLE_SUPER_ADMIN",
  },
  {
    id: 18,
    name: "Create Admin",
    icon: "fa fa-user-plus",
    to: "/superadmin/admins/new",
    role: "ROLE_SUPER_ADMIN",
  },
  {
    id: 21,
    name: "Settings",
    icon: "fa fa-cog",
    to: "/superadmin/settings",
    role: "ROLE_SUPER_ADMIN",
  },
];

export default SideBarLinks;
